### ISSUE TITLE
Softkeyboard appears again when pressing a Toggle on the same view

### ISSUE THREAD

**Issue by uholland** [art-technologies/swift-focuser#12]
I've got one TextField in my view which gets focus .onAppear. The Done button closes the Softkeyboard correctly. If I'm interacting with any Buttons, Toggles in the same List the last focused TextField gets focus again and the Softkeyboard appears unexpectedly.

**Comment by jonnyijapan** [comment]
Agreed. It seems like it refocuses the last focused textfield that used .focusedLegacy
So basically it seems that the modifier `FocusModifier` does not do the necessary updates of `focusedField` when the field is unselected, etc. Maybe this is same problem as #8 ?
